### ISSUE TITLE
GameProfile error on 1.20.2

### ISSUE THREAD

**Issue by 0xallie** [ChatTriggers/ctjs#79]
The mod works fine despite this, I don't know what this breaks.
```
Uncaught exception in thread "Thread-17"
[13:53:54] [Thread-17/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.class_320.method_1677()'
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at com.chattriggers.ctjs.api.client.Player.getUUID(Player.kt:140)
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at com.chattriggers.ctjs.CTJS.reportHashedUUID(CTJS.kt:50)
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at com.chattriggers.ctjs.CTJS.access$reportHashedUUID(CTJS.kt:28)
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at com.chattriggers.ctjs.CTJS$onInitializeClient$1$2.invoke(CTJS.kt:37)
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at com.chattriggers.ctjs.CTJS$onInitializeClient$1$2.invoke(CTJS.kt:35)
[13:53:54] [Thread-17/INFO]: [STDERR]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[13:53:54] [Thread-17/ERROR]: Uncaught exception in thread "Thread-17"
java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.class_320.method_1677()'
	at com.chattriggers.ctjs.api.client.Player.getUUID(Player.kt:140) ~[ctjs-3.0.0-beta.7_1.20.1-fabric.jar:?]
	at com.chattriggers.ctjs.CTJS.reportHashedUUID(CTJS.kt:50) ~[ctjs-3.0.0-beta.7_1.20.1-fabric.jar:?]
	at com.chattriggers.ctjs.CTJS.access$reportHashedUUID(CTJS.kt:28) ~[ctjs-3.0.0-beta.7_1.20.1-fabric.jar:?]
	at com.chattriggers.ctjs.CTJS$onInitializeClient$1$2.invoke(CTJS.kt:37) ~[ctjs-3.0.0-beta.7_1.20.1-fabric.jar:?]
	at com.chattriggers.ctjs.CTJS$onInitializeClient$1$2.invoke(CTJS.kt:35) ~[ctjs-3.0.0-beta.7_1.20.1-fabric.jar:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[org_jetbrains_kotlin_kotlin-stdlib-1.9.10-322b6d1b226d3ad5.jar:?]
```

**Comment by 0xallie** [comment]
I think the UniversalCraft version used by ChatTriggers needs to be updated.
